baseURL = "thesimplekid.github.io"
languageCode = "en-us"
title = "Brendan Murphy"
theme = "hugograyscale"
disableKinds = ["taxonomy", "taxonomyTerm"]


[params]
    copyright = "2021 Brendan Murphy"

